notify_pass: &notify_pass
  slack/notify:
    event: pass
    custom: |
      {
      	"blocks": [
      		{
      			"type": "section",
      			"text": {
      				"type": "mrkdwn",
      				"text": "The <https://github.com/jitsucom/jitsu/tree/$CIRCLE_BRANCH|$CIRCLE_BRANCH>* @ <https://github.com/jitsucom/jitsu/|jitsucom/jitsu> build has fixed!\n\nGreat job, *$CIRCLE_USERNAME*!"
      			},
      			"accessory": {
      				"type": "image",
      				"image_url": "https://media2.giphy.com/media/WsvLlmmjx9tnmeTPNc/giphy.gif?cid=ecf05e47h9ykneri13esdla2dpsk69ljttwqwqj7a3gchkll&rid=giphy.gif",
      				"alt_text": "Rocking cat"
      			}
      		},
      		{
      			"type": "actions",
      			"elements": [
      				{
      					"type": "button",
      					"text": {
      						"type": "plain_text",
      						"text": "View Details on CircleCI"
      					},
      					"url": "https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}"
      				}
      			]
      		}
      	]
      }

notify_fail: &notify_fail
  slack/notify:
    event: fail
    custom: |
      {
      	"blocks": [
      		{
      			"type": "section",
      			"text": {
      				"type": "mrkdwn",
      				"text": "Oh, no! The *<https://github.com/jitsucom/jitsu/tree/$CIRCLE_BRANCH|$CIRCLE_BRANCH>* @ <https://github.com/jitsucom/jitsu/|jitsucom/jitsu> build has failed. The last commit was authored by *$CIRCLE_USERNAME*. If that's you, please take a look!"
      			},
      			"accessory": {
      				"type": "image",
      				"image_url": "https://media4.giphy.com/media/NPUqgb8UE2iw8/giphy.gif",
      				"alt_text": "Sad cat"
      			}
      		},
      		{
      			"type": "actions",
      			"elements": [
      				{
      					"type": "button",
      					"text": {
      						"type": "plain_text",
      						"text": "View Details on CircleCI"
      					},
      					"url": "https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}"
      				}
      			]
      		}
      	]
      }

install_buildx: &install_buildx
  run:
    name: install docker buildx
    command: |
      mkdir -vp ~/.docker/cli-plugins/
      curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
      chmod a+x ~/.docker/cli-plugins/docker-buildx
      docker buildx version

build_ksense: &build_ksense
  run:
    name: Build and Push ksense EventNative Docker image
    command: |
      DOCKER_BUILDKIT=1 docker build --build-arg dhid=ksense -t $IMAGE_NAME:$IMAGE_VERSION -f $DOCKER_FILE .
      echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
      docker push $IMAGE_NAME

build_jitsu: &build_jitsu
  run:
    name: Build and Push jitsu Docker image
    command: |
      DOCKER_BUILDKIT=1  docker buildx build  --platform linux/amd64,linux/arm64 -t $IMAGE_NAME:$IMAGE_VERSION -f $DOCKER_FILE .
      echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
      docker push $IMAGE_NAME:$IMAGE_VERSION

version: 2.1

orbs:
  slack: circleci/slack@4.3.3

jobs:
  lint:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/jitsucom/jitsu
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-global-{{ checksum "./go.sum" }}
      - run: go get -u golang.org/x/lint/golint
      - run: golint ./...
      # uncomment it for stopping build on golint error
      # - run: golint -set_exit_status=true ./...
      - save_cache:
          key: go-mod-v1-global-{{ checksum "./go.sum" }}
          paths:
            - "/go/pkg/mod"
  server-test:
    working_directory: /go/src/github.com/jitsucom/jitsu/server
    docker:
      - image: circleci/golang:1.14
      - image: yandex/clickhouse-server:20.3
      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
      - image: circleci/redis
    environment:
      PG_TEST_PORT: 5432
      CH_TEST_PORT: 8123
      REDIS_TEST_PORT: 6379
      TEST_RESULTS: /tmp/test-results
      GO111MODULE: "on"
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          #docker_layer_caching: true it's requires upgrade plan
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "./server/go.sum" }}
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Waiting for Redis to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 6379 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Redis && exit 1
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            cd server && make test_backend | tee ${TEST_RESULTS}/go-test.out
      - store_test_results:
          path: /tmp/test-results
      - run: go mod tidy
      - save_cache:
          key: go-mod-v1-{{ checksum "./server/go.sum" }}
          paths:
            - "/go/pkg/mod"

  build-latest-en-docker:
    working_directory: /go/src/github.com/jitsucom/jitsu/
    environment:
      IMAGE_NAME: ksense/eventnative
      DOCKER_FILE: server.Dockerfile
      IMAGE_VERSION: latest
    docker:
      - image: cimg/go:1.14.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          #docker_layer_caching: true it's requires upgrade plan
      - <<: *build_ksense

  build-latest-jitsu-docker:
    working_directory: /go/src/github.com/jitsucom/jitsu/
    environment:
      IMAGE_NAME: jitsucom/server
      DOCKER_FILE: server.Dockerfile
      IMAGE_VERSION: latest
    docker:
      - image: cimg/go:1.14.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          #docker_layer_caching: true it's requires upgrade plan
      - <<: *install_buildx
      - <<: *build_jitsu
      - <<: *notify_fail
  build-latest-configurator-docker:
    working_directory: /go/src/github.com/jitsucom/jitsu/
    environment:
      IMAGE_NAME: jitsucom/configurator
      DOCKER_FILE: configurator.Dockerfile
      IMAGE_VERSION: latest
    docker:
      - image: cimg/go:1.14.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          #docker_layer_caching: true it's requires upgrade plan
      - <<: *install_buildx
      - <<: *build_jitsu
      - <<: *notify_fail
  build-beta-en-docker:
    working_directory: /go/src/github.com/jitsucom/jitsu/
    environment:
      IMAGE_NAME: ksense/eventnative
      DOCKER_FILE: server.Dockerfile
      IMAGE_VERSION: beta
    docker:
      - image: cimg/go:1.14.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          #docker_layer_caching: true it's requires upgrade plan
      - <<: *build_ksense

  build-beta-configurator-docker:
    working_directory: /go/src/github.com/jitsucom/jitsu/
    environment:
      IMAGE_NAME: jitsucom/configurator
      DOCKER_FILE: configurator.Dockerfile
      IMAGE_VERSION: beta
    docker:
      - image: cimg/go:1.14.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          #docker_layer_caching: true it's requires upgrade plan
      - <<: *install_buildx
      - <<: *build_jitsu
      - <<: *notify_fail
  build-beta-jitsu-docker:
    working_directory: /go/src/github.com/jitsucom/jitsu/
    environment:
      IMAGE_NAME: jitsucom/server
      DOCKER_FILE: server.Dockerfile
      IMAGE_VERSION: beta
    docker:
      - image: cimg/go:1.14.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          #docker_layer_caching: true it's requires upgrade plan
      - <<: *install_buildx
      - <<: *build_jitsu
      - <<: *notify_fail
  build-tagged-en-docker:
    working_directory: /go/src/github.com/jitsucom/jitsu/
    environment:
      IMAGE_NAME: ksense/eventnative
      DOCKER_FILE: server.Dockerfile
      IMAGE_VERSION: ${CIRCLE_TAG//v}
    docker:
      - image: cimg/go:1.14.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          #docker_layer_caching: true it's requires upgrade plan
      - <<: *build_ksense
  build-tagged-jitsu-docker:
    working_directory: /go/src/github.com/jitsucom/jitsu/
    environment:
      IMAGE_NAME: jitsucom/server
      DOCKER_FILE: server.Dockerfile
      IMAGE_VERSION: ${CIRCLE_TAG//v}
    docker:
      - image: cimg/go:1.14.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          #docker_layer_caching: true it's requires upgrade plan
      - <<: *install_buildx
      - <<: *build_jitsu
      - <<: *notify_fail
  build-tagged-configurator-docker:
    working_directory: /go/src/github.com/jitsucom/jitsu/
    environment:
      IMAGE_NAME: jitsucom/configurator
      DOCKER_FILE: configurator.Dockerfile
      IMAGE_VERSION: ${CIRCLE_TAG//v}
    docker:
      - image: cimg/go:1.14.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          #docker_layer_caching: true it's requires upgrade plan
      - <<: *install_buildx
      - <<: *build_jitsu
      - <<: *notify_fail

workflows:
  version: 2.1
  build-docker:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - server-test:
          context: jitsu
          requires:
            - lint
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - build-latest-en-docker:
          context: eventnative
          requires:
            - server-test
          filters:
            branches:
              only: master
      - build-latest-jitsu-docker:
          context: jitsu
          requires:
            - server-test
          filters:
            branches:
              only: master
      - build-latest-configurator-docker:
          context: jitsu
          requires:
            - server-test
          filters:
            branches:
              only: master
      - build-beta-en-docker:
          context: eventnative
          requires:
            - server-test
          filters:
            branches:
              only: beta
      - build-beta-jitsu-docker:
          context: jitsu
          requires:
            - server-test
          filters:
            branches:
              only: beta
      - build-beta-configurator-docker:
          context: jitsu
          requires:
            - server-test
          filters:
            branches:
              only: beta
      - build-tagged-en-docker:
          context: eventnative
          requires:
            - server-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-tagged-jitsu-docker:
          context: jitsu
          requires:
            - server-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-tagged-configurator-docker:
          context: jitsu
          requires:
            - server-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
